"""checking votes table

Revision ID: 189953bcc4d9
Revises: bf43e1e2c730
Create Date: 2024-11-13 09:43:40.201705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '189953bcc4d9'
down_revision: Union[str, None] = 'bf43e1e2c730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('temp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'temp')
    # ### end Alembic commands ###
